### ISSUE TITLE
Broken Activated Block leaves beam behind.

### ISSUE THREAD

**Issue by Chassx2** [DavidQF555/Beams#10]
While the beam is on and the block is broken it will leave the beam behind. No way as of current to remove this.
![2022-10-01_05 03 33](https://user-images.githubusercontent.com/56740526/193401999-c041df2f-5796-40d7-96b9-5df743106cd6.png)
![2022-10-01_05 03 35](https://user-images.githubusercontent.com/56740526/193402002-fecb68df-b7bc-4d7d-b876-b62968361936.png)
![2022-10-01_05 03 36](https://user-images.githubusercontent.com/56740526/193402007-62dc5eb5-29c2-40e3-a5a3-7f75778aa413.png)
![2022-10-01_05 03 45](https://user-images.githubusercontent.com/56740526/193402010-61c47fc3-473f-4f03-979b-f34e30d9228f.png)
![2022-10-01_05 03 49](https://user-images.githubusercontent.com/56740526/193402014-843fa9af-d09d-4d25-a773-483a0ce42a8a.png)
![2022-10-01_05 04 10](https://user-images.githubusercontent.com/56740526/193402016-70504d5f-e56c-40e3-9ec5-27c347de6a6f.png)

**Comment by DavidQF555** [comment]
Fixed in f1c59dd599e51e858995e63f035f3d562c10f560.
