### ISSUE TITLE
Show how many omnidirectional pointers are linked to each pointer

### ISSUE THREAD

**Issue by TheDeviantCrafter** [DavidQF555/Beams#8]
The projector pointer can link to multiple projectors. This is useful, but I kept forgetting to unlink. I would to see two changes:
1. Add a tooltip that shows the coordinates of each linked projector
2. When linking or unlinking a projector, show how many projectors are linked in the chat message.

It would also be nice if there was a way to unlink everything but I'm not sure what the best solution is.

**Comment by DavidQF555** [comment]
Added the tooltip in 863d4233b9873901445c618dd564f055d7466feb.
