### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by GentlemanCheeseMan** [DavidQF555/Beams#9]
Crash Log: https://pastebin.com/Cx8dmGcb

Heavily modded server crashing after activating projector. Only thing projector had in it was a red module. Crash doesn't happen in singeplayer. Haven't tested if the crash still happens without other mods installed.

Hope this is the right place to put this, mod looks really cool and I would love to have it on my server. Thank you :)

**Comment by DavidQF555** [comment]
Fixed in 69fe8eb87a9935e267503772a387834a50a9399c.
